// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfFYsnMIcU0kc18nFKcY5R4o7TFgfa-0',
    appId: '1:179888182988:web:86bec30b048d483db21469',
    messagingSenderId: '179888182988',
    projectId: 'bidding-7c695',
    authDomain: 'bidding-7c695.firebaseapp.com',
    storageBucket: 'bidding-7c695.appspot.com',
    measurementId: 'G-VMKMLFKPJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwj-A647RYJtbWRbZ13H_9yjq7B0IOKEI',
    appId: '1:179888182988:android:d8e61148051b9437b21469',
    messagingSenderId: '179888182988',
    projectId: 'bidding-7c695',
    storageBucket: 'bidding-7c695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20uNz6puePe-Z-XSBMpJ6dkR0aIYgk7Y',
    appId: '1:179888182988:ios:ab7d8b3693bc8265b21469',
    messagingSenderId: '179888182988',
    projectId: 'bidding-7c695',
    storageBucket: 'bidding-7c695.appspot.com',
    iosClientId: '179888182988-smp84dmkq9uh92gcdnjnbm8gn7919o9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bidding',
  );
}
